"""add deleted_at to todos

Revision ID: 63296e573b43
Revises: ca10ddc2fcef
Create Date: 2026-03-12 22:50:01.156051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63296e573b43'
down_revision: Union[str, Sequence[str], None] = 'ca10ddc2fcef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'deleted_at')
    # ### end Alembic commands ###
